# shellcheck shell=bash
# Cursor IDE → Inja LLM Gateway (same ChatGPT / Claude / SuperGrok subscriptions).
#
#   source examples/shell/claude-code-helpers.sh
#   source examples/shell/cursor-helpers.sh
#   export KEY=local-dev
#   cc-gateway-up
#   cursor-setup          # Settings → Models (keep Cursor built-ins + add gateway models)
#   cursor-models         # list only the custom names to Add Model
#   cursor-verify
#
# Cursor built-in models (Claude Fable 5, Composer 2.5, …) stay in the picker.
# Gateway models use PREFIXED names so they never collide:
#   claude/fable-5  → your Claude sub via llm-gateway
#   Claude Fable 5  → Cursor's own model

if ! command -v _inja_gateway_root >/dev/null 2>&1; then
  if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
    _INJA_SHELL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  elif [[ -n "${ZSH_VERSION:-}" ]]; then
    # shellcheck disable=SC2296
    _INJA_SHELL_DIR="$(cd "$(dirname "${(%):-%x}")" && pwd)"
  else
    _INJA_SHELL_DIR="$(pwd)/examples/shell"
  fi
  # shellcheck source=claude-code-helpers.sh
  source "$_INJA_SHELL_DIR/claude-code-helpers.sh"
fi

_cursor_base_url() {
  local g
  g="${GATEWAY:-$(_inja_cc_public_base 2>/dev/null || echo 'https://127.0.0.1:8787')}"
  g="${g%/}"
  if [[ "$g" == */v1 ]]; then
    printf '%s' "$g"
  else
    printf '%s/v1' "$g"
  fi
}

_cursor_key() {
  printf '%s' "${KEY:-${GATEWAY_EDGE_KEY:-local-dev}}"
}

# Recommended custom model names (prefixed — coexist with Cursor built-ins).
_cursor_gateway_models() {
  cat <<'EOF'
claude/fable-5
claude/fable
claude/sonnet-5
claude/sonnet
claude/opus
claude/opus-4-8
claude/haiku
claude/haiku-4-5
chatgpt/terra
chatgpt/sol
chatgpt/luna
chatgpt/gpt
grok/4.5
grok/grok-4.5
grok/composer-2.5
grok/build
inja/fable-5
inja/sonnet
inja/gpt
inja/sol
inja/grok-4.5
inja/composer-2.5
EOF
}

cursor-models() {
  cat <<EOF
── Cursor custom models (llm-gateway) ────────────────────────────
Add each line in Settings → Models → Add Model.
Leave Cursor's built-in models enabled (Claude Fable 5, Composer, …).

EOF
  _cursor_gateway_models
  cat <<EOF

Side-by-side example:
  Claude Fable 5     → Cursor product (Cursor billing)
  claude/fable-5     → Claude sub via llm-gateway
  Composer 2.5       → Cursor's Composer
  grok/composer-2.5  → SuperGrok Build via llm-gateway

Full list file: examples/cursor/models-to-add.txt
EOF
}

# Print copy-paste Cursor Settings → Models configuration.
cursor-setup() {
  local base key cert
  base="$(_cursor_base_url)"
  key="$(_cursor_key)"
  cert="$(_inja_cc_certs_dir 2>/dev/null)/localhost.pem"

  cat <<EOF

═══════════════════════════════════════════════════════════════════
  Cursor → Inja LLM Gateway  (built-ins + gateway models together)
═══════════════════════════════════════════════════════════════════

Yes — you can keep Cursor's own models AND add gateway models.

  Cursor built-in          llm-gateway custom (Add Model)
  ─────────────────        ────────────────────────────────
  Claude Fable 5           claude/fable-5   (your Claude sub)
  Claude Sonnet 5          claude/sonnet-5
  Composer 2.5             grok/composer-2.5 (SuperGrok Build)
  Cursor Grok 4.5          grok/4.5
  GPT-5.6 Terra (Cursor)   chatgpt/terra    (ChatGPT sub via gateway)

1) Gateway up:
     source examples/shell/claude-code-helpers.sh
     export KEY=$key
     cc-gateway-up

2) Cursor → Settings → Models

   A. Leave Cursor / Anthropic / Google built-ins ON
      (do not turn off Claude Fable 5 just because you add gateway Fable).

   B. Enable OpenAI API Key
        Paste:  $key
      (edge key — not a Platform sk-; gateway holds subscription OAuth)

   C. Enable Override OpenAI Base URL
        Paste:  $base
      (must end with /v1)
      This redirect applies to OpenAI-compatible / custom models you add.
      Cursor-native models (Composer, Cursor Grok, Cursor-routed Claude)
      stay on Cursor's side of the picker.

   D. Add Model for each gateway name (copy list: cursor-models):

$(_cursor_gateway_models | sed 's/^/        /')

   E. Optional: Verify, then pick either a Cursor built-in OR a
      claude/… chatgpt/… grok/… inja/… model in Chat / Agent.

3) TLS (self-signed): prefer mkcert -install
     cert: $cert

4) Combos (only add prefixes for subs you logged in):
   • ChatGPT:   chatgpt/terra chatgpt/sol chatgpt/luna
   • SuperGrok: grok/4.5 grok/composer-2.5
   • Claude:    claude/fable-5 claude/sonnet-5 claude/opus …

Health:
  curl -sk $(_cursor_base_url | sed 's|/v1$||')/healthz
  cursor-verify

Docs: https://inja-online.github.io/llm-gateway/guides/cursor-subscriptions/

═══════════════════════════════════════════════════════════════════
EOF
}

cursor-write-cheatsheet() {
  local root out base key
  root="$(_inja_gateway_root)"
  out="${1:-$root/examples/cursor/SETUP.md}"
  mkdir -p "$(dirname "$out")"
  base="$(_cursor_base_url)"
  key="$(_cursor_key)"
  cat >"$out" <<EOF
# Cursor → Inja LLM Gateway

Generated by \`cursor-write-cheatsheet\`.

## Coexistence

| In picker | Source |
|-----------|--------|
| Claude Fable 5, Composer 2.5, Cursor Grok | Cursor product |
| \`claude/fable-5\`, \`chatgpt/sol\`, \`grok/4.5\`, \`inja/…\` | llm-gateway + your subs |

## Settings → Models

| Field | Value |
|-------|-------|
| OpenAI API Key | \`$key\` |
| Override OpenAI Base URL | \`$base\` |

## Custom models to add

\`\`\`
$(_cursor_gateway_models)
\`\`\`

## Start gateway

\`\`\`bash
source examples/shell/claude-code-helpers.sh
export KEY=$key
cc-gateway-up
\`\`\`
EOF
  echo "wrote $out" >&2
}

cursor-verify() {
  local base key
  base="$(_cursor_base_url)"
  key="$(_cursor_key)"
  echo "GET $base/models (look for claude/fable-5, inja/…)" >&2
  curl -skS "$base/models" \
    -H "Authorization: Bearer $key" \
    -H "Content-Type: application/json" | head -c 4000
  echo
  if command -v jq >/dev/null 2>&1; then
    echo "── prefixed gateway ids ──" >&2
    curl -skS "$base/models" -H "Authorization: Bearer $key" \
      | jq -r '.data[].id' 2>/dev/null | grep -E '^(claude|chatgpt|grok|inja)/' | sort || true
  fi
}

cursor-print() { cursor-setup "$@"; }
cursor-help()  { cursor-setup "$@"; }
cursor-list-models() { cursor-models "$@"; }
