# shellcheck shell=bash
# Cursor IDE → Inja LLM Gateway (same ChatGPT / Claude / SuperGrok subscriptions).
#
#   source examples/shell/claude-code-helpers.sh   # HTTPS background gateway
#   source examples/shell/cursor-helpers.sh
#   export KEY=local-dev
#   cc-gateway-up
#   cursor-setup          # print Settings → Models values
#   cursor-open-docs      # open the website guide (if available)
#
# Cursor only accepts an OpenAI-compatible base URL in Settings (GUI).
# These helpers print the exact fields and model names to paste.

# Prefer shared paths from claude-code-helpers when already sourced.
if ! command -v _inja_gateway_root >/dev/null 2>&1; then
  if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
    _INJA_SHELL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  elif [[ -n "${ZSH_VERSION:-}" ]]; then
    # shellcheck disable=SC2296
    _INJA_SHELL_DIR="$(cd "$(dirname "${(%):-%x}")" && pwd)"
  else
    _INJA_SHELL_DIR="$(pwd)/examples/shell"
  fi
  # shellcheck source=claude-code-helpers.sh
  source "$_INJA_SHELL_DIR/claude-code-helpers.sh"
fi

_cursor_base_url() {
  local g
  g="${GATEWAY:-$(_inja_cc_public_base 2>/dev/null || echo 'https://127.0.0.1:8787')}"
  # Cursor appends /chat/completions (and /responses) under this base.
  # Must include /v1 — do not add a trailing slash after v1 inconsistently.
  g="${g%/}"
  if [[ "$g" == */v1 ]]; then
    printf '%s' "$g"
  else
    printf '%s/v1' "$g"
  fi
}

_cursor_key() {
  printf '%s' "${KEY:-${GATEWAY_EDGE_KEY:-local-dev}}"
}

# Print copy-paste Cursor Settings → Models configuration.
cursor-setup() {
  local base key cert
  base="$(_cursor_base_url)"
  key="$(_cursor_key)"
  cert="$(_inja_cc_certs_dir 2>/dev/null)/localhost.pem"

  cat <<EOF

═══════════════════════════════════════════════════════════════════
  Cursor → Inja LLM Gateway (subscription models)
═══════════════════════════════════════════════════════════════════

1) Start the gateway (if not already):
     source examples/shell/claude-code-helpers.sh
     export KEY=$key
     cc-gateway-up

2) Cursor → Settings → Models

   • Enable  OpenAI API Key
     Paste:  $key

   • Enable  Override OpenAI Base URL
     Paste:  $base
     (must end with /v1)

   • Add models (name must match gateway aliases or provider/model):

       gpt
       gpt-mini
       o3
       grok-4.5
       composer-2.5
       sonnet
       opus
       haiku

     Optional full ids:
       chatgpt/gpt-5.1
       xai/grok-4.5
       xai/composer-2.5
       anthropic/claude-sonnet-4-20250514

   • Click Verify (if shown), then select the model in the chat/agent picker.

3) TLS trust (self-signed only; skip if you used mkcert -install):
     export NODE_EXTRA_CA_CERTS=$cert
     # Cursor is an Electron/Node app — system trust from mkcert is preferred.
     # If Verify fails on certificate errors, re-run:
     #   brew install mkcert && mkcert -install
     #   ./examples/scripts/gen-localhost-tls.sh
     #   cc-gateway-down && cc-gateway-up

4) What works
   • Chat / Plan / Ask with custom OpenAI base URL
   • Agent mode may use the OpenAI Responses API — this gateway exposes
     POST /v1/responses for openai / openai_compat providers (ChatGPT, xAI)
   • Claude-shaped models are reached by model id (translate or passthrough)

5) Combos (which models you "have")
   • GPT only:        use gpt / o3 / gpt-mini
   • Grok only:       use grok-4.5 / composer-2.5
   • GPT + Grok:      both families above
   • + Claude:        add sonnet / opus / haiku (needs auth login claude)

Health check:
  curl -sk $(_cursor_base_url | sed 's|/v1$||')/healthz

Full guide (docs site):
  https://inja-online.github.io/llm-gateway/guides/cursor-subscriptions/

═══════════════════════════════════════════════════════════════════
EOF
}

# Write a short Markdown cheatsheet next to certs (optional convenience).
cursor-write-cheatsheet() {
  local root out base key
  root="$(_inja_gateway_root)"
  out="${1:-$root/examples/cursor/SETUP.md}"
  mkdir -p "$(dirname "$out")"
  base="$(_cursor_base_url)"
  key="$(_cursor_key)"
  cat >"$out" <<EOF
# Cursor → Inja LLM Gateway

Generated by \`cursor-write-cheatsheet\`. Do not commit secrets.

## Settings → Models

| Field | Value |
|-------|-------|
| OpenAI API Key | \`$key\` |
| Override OpenAI Base URL | \`$base\` |

## Models to add

- \`gpt\`, \`gpt-mini\`, \`o3\`
- \`grok-4.5\`, \`composer-2.5\`
- \`sonnet\`, \`opus\`, \`haiku\` (Claude subscription)

## Start gateway

\`\`\`bash
source examples/shell/claude-code-helpers.sh
export KEY=$key
cc-gateway-up
\`\`\`

## Notes

- Cursor appends paths under the base URL; keep the \`/v1\` suffix.
- Agent mode may call \`/v1/responses\` (supported for ChatGPT / xAI openai_compat).
- Prefer \`mkcert -install\` for local HTTPS trust.
EOF
  echo "wrote $out" >&2
}

# Smoke: list models from the gateway (OpenAI catalog shape).
cursor-verify() {
  local base key
  base="$(_cursor_base_url)"
  key="$(_cursor_key)"
  echo "GET $base/models" >&2
  curl -skS "$base/models" \
    -H "Authorization: Bearer $key" \
    -H "Content-Type: application/json" | head -c 2000
  echo
}

# Aliases
cursor-print() { cursor-setup "$@"; }
cursor-help()  { cursor-setup "$@"; }
